export const ADMIN_ZH = {
  "Mattex Marketplace Admin Portal": "Mattex 市集後台",
  Marketplace: "市集",
  "Staff only": "只限同事",
  "Mattex Sales portal": "Mattex 銷售後台",
  "Product ops, Excel, buyer accounts, RFQ review, TMS upload.": "產品、Excel、買家帳戶、RFQ 審核、TMS 上載。",
  Email: "電郵",
  Password: "密碼",
  "This email is a buyer account.": "此電郵是買家帳戶。",
  "This account still needs to set a password from the invite email.": "此帳戶仍需用邀請電郵設定密碼。",
  "Portal sign-in is not configured on this server.": "此伺服器未設定後台登入。",
  "Sign-in failed.": "登入失敗。",
  "Signing in…": "登入中…",
  "Enter portal": "進入後台",
  "Forgot password?": "忘記密碼？",
  "RFQ inbox": "RFQ 收件箱",
  Products: "產品",
  Banners: "橫幅",
  Accounts: "帳戶",
  "Mattex Products": "Mattex 產品",
  "Product Category": "產品分類",
  "Mattex Chain Products": "Mattex Chain 產品",
  Soon: "即將推出",
  Sales: "銷售",
  Buyer: "買家",
  "Change password": "更改密碼",
  "Log out": "登出",
  "Mattex operations": "Mattex 操作",
  "Same marketplace catalog — this portal only adds product / RFQ ops.": "與市集同一份目錄。此後台只處理產品和 RFQ。",
  "New marketplace alert": "新市集提示",
  Jump: "前往",
  Close: "關閉",
  All: "全部",
  Active: "使用中",
  Invited: "已邀請",
  Disabled: "已停用",
  Rejected: "已拒絕",
  Published: "已上架",
  Unpublish: "已下架",
  Removed: "已移除",
  Pending: "待處理",
  Received: "已收到",
  Reviewing: "審核中",
  "Reverse requested": "申請撤回",
  "Cancel requested": "申請取消",
  Accepted: "已接受",
  "iRFQ created": "已建立 iRFQ",
  Revising: "修改中",
  Returned: "已退回",
  Quoted: "已報價",
  "No Offer Rejected": "無法報價並拒絕",
  Cancelled: "已取消",
  "In review": "處理中",
  "WhatsApp quote": "WhatsApp 報價",
  "No marketplace account": "沒有市集帳戶",
  "Provisional SKU ID": "臨時 SKU",
  Category: "分類",
  "IMG + Product name": "圖片及產品名稱",
  Name: "名稱",
  "Size / Description": "尺寸／說明",
  "Certifications / Relevant Reports": "認證／相關報告",
  "Primary Spec Description": "主要規格說明",
  "Tag (Green / Hit / Tailor Made)": "標籤（綠色／熱門／訂製）",
  "Sales Unit": "銷售單位",
  Unit: "單位",
  MOQ: "最低訂購量",
  "Lead Time": "交貨期",
  "Lead time": "交貨期",
  "Purposes (Indicator for Searching)": "用途（搜尋提示）",
  Remark: "備註",
  "Duplicate SKU": "SKU 重複",
  "Sign in as sales staff to change this.": "請以銷售同事身份登入後再改。",
  "Unpublish this product before Delete forever.": "請先下架，才可永久刪除。",
  "Enter a rejection reason.": "請填寫拒絕原因。",
  "Move products out of this category first.": "請先把產品移出此分類。",
  "Email is not set up on this computer. The RFQ change was saved.": "此電腦未設定電郵。RFQ 變更已儲存。",
  "Unable to save": "未能儲存",
  Saved: "已儲存",
  "Search RFQ no., buyer, product, TMS…": "搜尋 RFQ 編號、買家、產品、TMS…",
  "Search name, SKU, category, purpose…": "搜尋名稱、SKU、分類、用途…",
  "Search name, SKU, category…": "搜尋名稱、SKU、分類…",
  "Search name, email, company…": "搜尋名稱、電郵、公司…",
  "Search products in this category…": "搜尋此分類的產品…",
  "Search company, name or email…": "搜尋公司、名稱或電郵…",
  "Search name or email…": "搜尋名稱或電郵…",
  "Add a category to get started.": "先新增一個分類。",
  "Add, rename, or delete empty categories. Hover Delete to see why a category cannot be removed.": "可新增、改名或刪除空的分類。刪除不能按時，滑鼠移上去可看原因。",
  "After confirm, the buyer cannot be changed. The RFQ moves to that member’s My RFQs.": "確認後不能再改買家。此 RFQ 會轉到該會員的「我的 RFQ」。",
  "Buyer RFQ status will become No Offer Rejected.": "買家的 RFQ 狀態會變成「無法報價並拒絕」。",
  "Buyer asked to cancel. Accept to close, or keep the RFQ.": "買家申請取消。接受即結束，或保留此 RFQ。",
  "Can log in now. Disable to pause, or Reject to refuse the account.": "現在可以登入。停用是暫停，拒絕是不接受此帳戶。",
  "Delete forever removes the login. RFQs stay with this name and email frozen.": "永久刪除會移除登入。RFQ 仍保留此名稱和電郵。",
  "Download a copy of this RFQ.": "下載此 RFQ 副本。",
  "No import yet.": "尚未匯入。",
  "No marketplace account for this email.": "此電郵沒有市集帳戶。",
  "No matching members": "沒有相符會員",
  "No reports. Buyers file them on the original product detail page.": "沒有報告。買家在產品內頁提出。",
  "Select a reason above or write your own": "選上面的原因，或自行填寫",
  "Select all products in this category": "選取此分類全部產品",
  "Select all products to add": "選取要加入的全部產品",
  "Select all visible products": "選取畫面上的全部產品",
  "Select at least two products": "請至少選兩件產品",
  "Showing first 80 matches. Search to narrow.": "先顯示 80 個結果。可再搜尋收窄。",
  "They cannot log in. This cannot be reversed with Enable. A rejection email will open.": "對方將不能登入，也不能再啟用。系統會打開拒絕電郵。",
  "This cannot be undone.": "此操作不能還原。",
  "Viewing a previous RFQ request. Switch to Current to see the latest submission.": "正在查看舊的 RFQ。切換到「目前」才看到最新提交。",
  "Why this account is refused": "拒絕此帳戶的原因",
  "Worksheet edits stay draft until Submit To Buyer or Quote sent on WhatsApp.": "工作表的修改在「提交給買家」或「WhatsApp 已發送報價」之前都是草稿。",
  "Accept the RFQ first.": "請先接受此 RFQ。",
  "Accepted. Buyer sees In review. Follow up by phone if needed.": "已接受。買家看到「處理中」。如有需要請致電跟進。",
  "Accepted. Enter prices, then Submit To Buyer or Create TMS iRFQ.": "已接受。請輸入價格，然後提交給買家或建立 TMS iRFQ。",
  "Accepted. Quote sent on WhatsApp — assign a member or update the WhatsApp quote.": "已接受。報價已由 WhatsApp 送出。可指派會員，或更新 WhatsApp 報價。",
  "Acknowledge the RFQ first": "請先確認此 RFQ",
  "Acknowledge this RFQ to start handling it, or Reject (No Offer).": "確認此 RFQ 後開始處理，或拒絕（無法報價）。",
  "Acknowledge to price this RFQ, or Reject (No Offer).": "確認後為此 RFQ 報價，或拒絕（無法報價）。",
  Action: "操作",
  Activity: "活動",
  "Add Product": "新增產品",
  "Add a number…": "輸入號碼…",
  "Add a parseable phone in Follow-up first": "請先在跟進欄輸入可辨識的電話",
  "Add a parseable phone in Follow-up first.": "請先在跟進欄輸入可辨識的電話。",
  "Add photo": "加入相片",
  Address: "地址",
  "Another sales account must Delete forever.": "必須由另一個銷售帳戶執行永久刪除。",
  Attachment: "附件",
  Bootstrap: "初始帳戶",
  "Building…": "產生中…",
  "Buyer asked to cancel this RFQ.": "買家申請取消此 RFQ。",
  "Buyer asked to reverse this RFQ so they can revise it.": "買家申請撤回此 RFQ，以便修改。",
  "Buyer disabled": "買家已停用",
  "Buyer email could not be sent.": "未能發送買家電郵。",
  "Buyer email sent.": "已發送買家電郵。",
  "Buyer email was not sent. Email is not set up on this computer.": "未發送買家電郵。此電腦未設定電郵。",
  "Buyer enabled": "買家已啟用",
  "Buyer products": "買家產品",
  "Buyer report": "買家報告",
  "Buyer status": "買家狀態",
  Call: "致電",
  "Cancel accepted": "已接受取消",
  "Cancel accepted. Buyer email could not be sent.": "已接受取消。未能發送買家電郵。",
  "Cancel accepted. Buyer email sent.": "已接受取消。已發送買家電郵。",
  "Cannot delete the last category.": "不能刪除最後一個分類。",
  "Cannot supply": "未能供應",
  Cards: "卡片",
  Channel: "渠道",
  "Click WhatsApp to open WhatsApp, or WeChat to open WeChat.": "按 WhatsApp 打開 WhatsApp，或按 WeChat 打開微信。",
  "Click WhatsApp or WeChat to open that app. A number without those options is a phone number — click to call.": "按 WhatsApp 或微信打開該程式。沒有這兩個選項的號碼是電話，按一下即可致電。",
  "Click the number to call.": "按號碼即可致電。",
  "Click the number to open WeChat.": "按號碼即可打開微信。",
  "Click the number to open WhatsApp.": "按號碼即可打開 WhatsApp。",
  Company: "公司",
  "Company phone": "公司電話",
  "Company reg.": "公司登記",
  "Confirm Restore": "確認還原",
  "Confirm Unpublish (take offline)": "確認下架",
  "Confirm assign buyer": "確認指派買家",
  "Confirm publish (go live)": "確認上架",
  "Confirm these products before the change is applied.": "確認這些產品後才會套用變更。",
  "Contact number cleared": "已清除聯絡電話",
  "Contact number saved": "已儲存聯絡電話",
  Contact: "聯絡",
  Contractor: "承辦商",
  "Could not load this version into draft.": "未能把此版本載入草稿。",
  Count: "數量",
  "Create TMS iRFQ": "建立 TMS iRFQ",
  "Creating iRFQ…": "正在建立 iRFQ…",
  "Current password is incorrect.": "目前密碼不正確。",
  "Delete forever": "永久刪除",
  "Deleted forever": "已永久刪除",
  "Disable or Reject this buyer first.": "請先停用或拒絕此買家。",
  "Disable this account first.": "請先停用此帳戶。",
  "Download PDF": "下載 PDF",
  "Drop to upload": "放開以上載",
  "Each image must be under 800 KB after compress (max 1,600px).": "每張圖片壓縮後須少於 800 KB（最長邊 1,600px）。",
  "Edit category": "編輯分類",
  "Edit selected product": "編輯已選產品",
  "Enter a category name.": "請輸入分類名稱。",
  "Enter a name.": "請輸入名稱。",
  "Enter a price for every line before submitting to the buyer.": "提交給買家前，每一行都要有價格。",
  "Enter a price for every offer line first": "請先為每一行報價填價格",
  "Enter a price for every offer line first.": "請先為每一行報價填價格。",
  "Enter a price, or choose Price Upon Request.": "請輸入價格，或選「另行報價」。",
  "Enter a unit price for each line, then Submit To Buyer or Create TMS iRFQ.": "請為每一行輸入單價，然後提交給買家或建立 TMS iRFQ。",
  "Enter a valid email.": "請輸入有效電郵。",
  "Enter your current password.": "請輸入目前密碼。",
  "Excel import finished.": "Excel 匯入完成。",
  "Fixed + Unpublish — hidden from marketplace": "已修正並下架，市集上看不到",
  "Fixed — click Publish when ready": "已修正。準備好後按上架",
  "Follow-up": "跟進",
  "Go to RFQ": "前往 RFQ",
  Green: "綠色",
  Guest: "訪客",
  "Guest RFQ has no marketplace phone. Add a number, then click it to open WhatsApp.": "訪客 RFQ 沒有市集電話。請先加號碼，再按號碼打開 WhatsApp。",
  "Guest has no marketplace account. Assign a member or WhatsApp the quote.": "訪客沒有市集帳戶。請指派會員，或用 WhatsApp 發送報價。",
  "Guest has no marketplace account. Assign a member, or WhatsApp the quote.": "訪客沒有市集帳戶。請指派會員，或用 WhatsApp 發送報價。",
  "Guest has no marketplace account. Send quote on WhatsApp, or assign a member.": "訪客沒有市集帳戶。請用 WhatsApp 發送報價，或指派會員。",
  "Guest quote was not created.": "未能建立訪客報價。",
  Hit: "熱門",
  Ignored: "已忽略",
  Import: "匯入",
  "Import Excel": "匯入 Excel",
  "Importing…": "匯入中…",
  "Invite staff": "邀請同事",
  "Item marked no offer": "此項已標為無法報價",
  "JPG / PNG / WebP · up to 5 photos · longest side 1,600px · max 800 KB each after compress.": "JPG／PNG／WebP · 最多 5 張 · 最長邊 1,600px · 壓縮後每張最多 800 KB。",
  "Keep at least one active sales account.": "至少保留一個使用中的銷售帳戶。",
  Lead: "交貨期",
  List: "列表",
  "Load this version into draft? Unsaved worksheet prices will be overwritten.": "把此版本載入草稿？未儲存的工作表價格會被覆蓋。",
  "Localhost does not send the buyer email.": "本機不會發送買家電郵。",
  "Mark this quote as sent on WhatsApp (does not submit to My RFQs)": "標記此報價已由 WhatsApp 送出（不會提交到「我的 RFQ」）",
  Member: "會員",
  Mobile: "手機",
  "Move or restore products out of this category first.": "請先把產品移出或還原，離開此分類。",
  "New category name": "新分類名稱",
  "New password must be different.": "新密碼不能與舊密碼相同。",
  "No Excel file selected.": "未選擇 Excel 檔。",
  "No RFQs in this status.": "此狀態沒有 RFQ。",
  "No RFQs match this search.": "沒有相符的 RFQ。",
  "No Unpublish products to go live.": "沒有可上架的下架產品。",
  "No accounts in this status.": "此狀態沒有帳戶。",
  "No accounts match this search.": "沒有相符的帳戶。",
  "No buyer email (guest or invalid address).": "沒有買家電郵（訪客或電郵無效）。",
  "No offer": "無法報價",
  "No products in this category.": "此分類沒有產品。",
  "No products in this status.": "此狀態沒有產品。",
  "No products match this search.": "沒有相符的產品。",
  "No registered buyers yet.": "尚未有註冊買家。",
  "No sales accounts yet.": "尚未有銷售帳戶。",
  "Nothing published. Need official SKU, name, unit, category, and a unique SKU.": "沒有上架。需要正式 SKU、名稱、單位、分類，以及不重複的 SKU。",
  "Offer restored": "已恢復報價",
  "Open WeChat": "打開微信",
  "Open WhatsApp": "打開 WhatsApp",
  "Open WhatsApp chat": "打開 WhatsApp 對話",
  "Open WhatsApp first, then mark sent": "請先打開 WhatsApp，再標記已發送",
  "Open WhatsApp first, then mark sent.": "請先打開 WhatsApp，再標記已發送。",
  "Open product": "打開產品",
  "Opening…": "打開中…",
  "Other phone": "其他電話",
  "Out of stock": "缺貨",
  "Password needs 8+ characters, a letter, and a number.": "密碼至少 8 個字，並包含字母和數字。",
  "Password updated.": "密碼已更新。",
  "Passwords do not match.": "兩次密碼不相同。",
  Phone: "電話",
  "Photo must be WebP.": "相片必須是 WebP。",
  "Please choose an image file.": "請選擇圖片檔。",
  "Please enter a product name.": "請輸入產品名稱。",
  Price: "價格",
  "Price Upon Request": "另行報價",
  "Price cleared": "已清除價格",
  "Price lines · Draft": "價格行 · 草稿",
  "Price lines · read-only preview": "價格行 · 只讀預覽",
  "Price saved": "價格已儲存",
  "Priced. Guest cannot receive this in marketplace My RFQs.": "已填價格。訪客不能在市集「我的 RFQ」收到。",
  Product: "產品",
  "Product images": "產品圖片",
  "Product not found in catalog": "目錄找不到此產品",
  "Product reports": "產品報告",
  "Product status": "產品狀態",
  Project: "項目",
  "Qty saved": "數量已儲存",
  Qty: "數量",
  "Quantity too low": "數量太少",
  "Quote is with the buyer. You can update prices or Create TMS iRFQ.": "報價已交給買家。可更新價格，或建立 TMS iRFQ。",
  "Quote marked sent on WhatsApp (not submitted to My RFQs)": "已標記報價由 WhatsApp 送出（未提交到「我的 RFQ」）",
  "Quote sent to buyer.": "報價已送給買家。",
  "Quote submitted to buyer": "報價已提交給買家",
  RFQ: "RFQ",
  "RFQ accepted — buyer sees In review. Follow up by phone if needed.": "RFQ 已接受。買家看到「處理中」。如有需要請致電跟進。",
  "RFQ accepted — enter prices, then Submit To Buyer or Create TMS iRFQ": "RFQ 已接受。請輸入價格，然後提交給買家或建立 TMS iRFQ",
  "RFQ accepted. Buyer email could not be sent.": "RFQ 已接受。未能發送買家電郵。",
  "RFQ accepted. Buyer email sent. Enter prices, then Submit To Buyer or Create TMS iRFQ.": "RFQ 已接受。已發送買家電郵。請輸入價格，然後提交給買家或建立 TMS iRFQ。",
  "RFQ accepted. Buyer sees In review. Follow up by phone if needed.": "RFQ 已接受。買家看到「處理中」。如有需要請致電跟進。",
  "RFQ assigned to member": "RFQ 已指派給會員",
  "RFQ kept": "已保留 RFQ",
  "RFQ kept in In review. Buyer email sent.": "RFQ 維持處理中。已發送買家電郵。",
  "RFQ kept. Buyer email could not be sent.": "已保留 RFQ。未能發送買家電郵。",
  "RFQ marked No Offer Rejected": "RFQ 已標為無法報價並拒絕",
  "RFQ moved to In review. Buyer email sent.": "RFQ 已轉為處理中。已發送買家電郵。",
  "RFQ moved to No Offer Rejected. Buyer email sent.": "RFQ 已轉為無法報價並拒絕。已發送買家電郵。",
  "RFQ rejected. Buyer email could not be sent.": "RFQ 已拒絕。未能發送買家電郵。",
  "RFQ status": "RFQ 狀態",
  "RFQ view": "RFQ 檢視",
  "Reject buyer": "拒絕買家",
  "Rejection email sent": "已發送拒絕電郵",
  "Remark saved": "備註已儲存",
  "Remove from catalog": "從目錄移除",
  "Removed SKUs leave the marketplace (soft delete) until Restore.": "移除的 SKU 會離開市集（軟刪除），直至還原。",
  "Removed from catalog": "已從目錄移除",
  "Restore takes the SKU out of Removed. It becomes Unpublish and does not go live.": "還原會把 SKU 移出「已移除」。它會變成已下架，不會直接上架。",
  "Restore this product before Publish.": "請先還原此產品，才可上架。",
  "Restored as Unpublish": "已還原為下架",
  "Reverse accepted": "已接受撤回",
  "Reverse accepted. Buyer can revise. Email sent.": "已接受撤回。買家可以修改。電郵已發送。",
  "Reverse accepted. Buyer email could not be sent.": "已接受撤回。未能發送買家電郵。",
  Roles: "角色",
  "Row results": "列結果",
  SKU: "SKU",
  Save: "儲存",
  "Sales status": "銷售狀態",
  "Search RFQs": "搜尋 RFQ",
  "Search buyers": "搜尋買家",
  "Search in category": "在分類中搜尋",
  "Search products": "搜尋產品",
  "Search sales": "搜尋銷售",
  "Select Published products to Unpublish.": "請選擇已上架產品來下架。",
  "Select Removed products to Restore.": "請選擇已移除產品來還原。",
  "Select Unpublish or Removed products to Delete forever. Unpublish live SKUs first.": "請選擇已下架或已移除的產品來永久刪除。上架中的 SKU 要先下架。",
  "Select Unpublish products to Publish.": "請選擇已下架產品來上架。",
  "Select one product to edit": "請選擇一件產品來編輯",
  "Select one product to edit.": "請選擇一件產品來編輯。",
  "Select products and a destination category.": "請選擇產品和目標分類。",
  "Select products to add.": "請選擇要加入的產品。",
  "Select products to remove (soft delete).": "請選擇要移除的產品（軟刪除）。",
  "Send invite": "發送邀請",
  "Send quote on WhatsApp": "用 WhatsApp 發送報價",
  "Set price": "設定價格",
  "Spec not available": "沒有規格",
  Staff: "同事",
  Status: "狀態",
  "Submit To Buyer": "提交給買家",
  "Submitting…": "提交中…",
  "TMS create failed": "建立 TMS 失敗",
  "Tailor Made": "訂製",
  "Tailor Made Product": "訂製產品",
  Tags: "標籤",
  "That category already exists.": "此分類已存在。",
  "That email is already in use.": "此電郵已在使用。",
  "This RFQ already belongs to a marketplace account and cannot be reassigned.": "此 RFQ 已屬於市集帳戶，不能再指派。",
  "This marketplace account has no phone number. Add a number in this slot.": "此市集帳戶沒有電話。請在此欄加上號碼。",
  Type: "類型",
  "Unable to Delete forever. Unpublish live SKUs first.": "未能永久刪除。請先下架上架中的 SKU。",
  "Unable to Unpublish": "未能下架",
  "Unable to Unpublish selected products.": "未能下架所選產品。",
  "Unable to add category.": "未能新增分類。",
  "Unable to add product.": "未能新增產品。",
  "Unable to add products.": "未能加入產品。",
  "Unable to build PDF": "未能產生 PDF",
  "Unable to delete.": "未能刪除。",
  "Unable to freeze this quote.": "未能凍結此報價。",
  "Unable to invite staff.": "未能邀請同事。",
  "Unable to move products.": "未能移動產品。",
  "Unable to read Excel file.": "未能讀取 Excel 檔。",
  "Unable to reject.": "未能拒絕。",
  "Unable to rename.": "未能改名。",
  "Unable to restore selected products.": "未能還原所選產品。",
  "Unable to save the group": "未能儲存此組",
  "Unable to save.": "未能儲存。",
  "Unable to update selected products.": "未能更新所選產品。",
  "Unable to update the group": "未能更新此組",
  "Undo no offer": "取消無法報價",
  "Update quote on WhatsApp": "更新 WhatsApp 報價",
  "Update quote to buyer": "更新給買家的報價",
  "Update the display name. Email cannot be changed.": "可更新顯示名稱。電郵不能更改。",
  "Update the display name. They still set a password from the invite email.": "可更新顯示名稱。對方仍要用邀請電郵設定密碼。",
  "We'll open an email so they can set their own password. No temporary password is created.": "系統會打開電郵，讓對方自行設定密碼。不會建立臨時密碼。",
  WeChat: "微信",
  WhatsApp: "WhatsApp",
  PDF: "PDF",
  Ready: "就緒",
  "No image": "沒有圖片",
  "Category name": "分類名稱",
  "e.g. 100": "例如 100",
  "e.g. 125": "例如 125",
  "e.g. 14 days": "例如 14 天",
  "e.g. 500 × 500 × 80mm": "例如 500 × 500 × 80mm",
  "e.g. Also known as…": "例如又稱…",
  "e.g. Density 1100 & 1200kg/m³, compressive strength…": "例如密度 1100 及 1200kg/m³、抗壓強度…",
  "e.g. Gypsum Block — 500×500×80mm": "例如石膏磚 — 500×500×80mm",
  "e.g. ISO 9001, HKGBC Green": "例如 ISO 9001、HKGBC 綠色",
  "e.g. MKT-GB-0001": "例如 MKT-GB-0001",
  "e.g. confirm size / lead": "例如確認尺寸／交貨期",
  "e.g. m², pcs, sheet": "例如 m²、件、張",
  "Enter your work email.": "請輸入工作電郵。",
  "Forgot password": "忘記密碼",
  "Enter your portal email. If the account exists, we will send a reset link.": "請輸入後台電郵。若帳戶存在，我們會發送重設連結。",
  "If this email has a portal account, a reset link is on the way. Check your inbox.": "若此電郵有後台帳戶，重設連結已寄出。請查看收件箱。",
  "Back to sign in": "返回登入",
  "Send reset link": "發送重設連結",
  "Reset your password": "重設密碼",
  "Set your password": "設定密碼",
  "Checking link…": "正在檢查連結…",
  "This link is not valid.": "此連結無效。",
  "This link is not valid. Ask a teammate to send a new invite or reset email.": "此連結無效。請同事再發邀請或重設電郵。",
  "This link has expired. Request a new reset email.": "此連結已過期。請再申請重設電郵。",
  "This link has expired. Request a new reset email from the sign-in page.": "此連結已過期。請在登入頁再申請重設電郵。",
  "New password": "新密碼",
  "Confirm password": "確認密碼",
  "Save password and enter portal": "儲存密碼並進入後台",
  "Already set a password?": "已經設定密碼？",
  "Sign in": "登入",
  "Loading banners…": "正在載入橫幅…",
  "Unsaved changes": "有未儲存的變更",
  "Show on marketplace": "在市集顯示",
  "Saving…": "儲存中…",
  "Unsaved changes. Not on the marketplace until you Save.": "有未儲存的變更。按儲存後才會出現在市集。",
  "Hidden on marketplace": "市集上已隱藏",
  "Homepage limited-offer title and description. A blank title shows 限時優惠 / Limited offer. Banner names stay on the offer page.": "首頁限時優惠的標題和說明。標題留空會顯示「限時優惠／Limited offer」。橫幅名稱仍在優惠頁。",
  "Title（中文）": "標題（中文）",
  "Title (English)": "標題（English）",
  "Description（中文）": "說明（中文）",
  "Description (English)": "說明（English）",
  "Demo preview": "預覽",
  Homepage: "首頁",
  "Banner list": "橫幅列表",
  "Row 1 is the homepage banner. Drag a row to the top to change it. Not on the marketplace until you Save.": "第 1 行是首頁橫幅。拖到最上面即可更換。按儲存後才會出現在市集。",
  Image: "圖片",
  "Tab name (中文)": "分頁名稱（中文）",
  "Tab name (English)": "分頁名稱（English）",
  "Confirm delete": "確認刪除",
  Delete: "刪除",
  "Products on this banner": "此橫幅的產品",
  "No limit. Each product needs a promo price and an end date, and can belong to only one banner.": "沒有上限。每件產品要有優惠價和結束日期，而且只能屬於一個橫幅。",
  "Promo price": "優惠價",
  "End date": "結束日期",
  Remove: "移除",
  "Search product name, SKU, or category": "搜尋產品名稱、SKU 或分類",
  "Drop to add": "放開以加入",
  "Release to add": "放開以加入",
  "Add banner": "新增橫幅",
  "Drop a JPG, PNG, or WebP here, or click to choose files. Saved as WebP, longest side 2,400px.": "把 JPG、PNG 或 WebP 拖到這裡，或按一下選擇檔案。會存成 WebP，最長邊 2,400px。",
  "Image is still too large after WebP.": "轉成 WebP 後仍然太大。",
  "Use a JPG, PNG, or WebP.": "請使用 JPG、PNG 或 WebP。",
  "Could not read that image.": "未能讀取此圖片。",
  "Banner image must be WebP.": "橫幅圖片必須是 WebP。",
  "Skip — need": "略過 — 需要",
  "Will publish · missing": "將會上架 · 尚欠",
  "Cannot publish. Need": "未能上架。需要",
  Publish: "上架",
  Restore: "還原",
  Edit: "編輯",
  Add: "新增",
  Cancel: "取消",
  Confirm: "確認",
  Enable: "啟用",
  Disable: "停用",
  Reject: "拒絕",
  Assign: "指派",
  Draft: "草稿",
  Current: "目前",
  "Quote sent on WhatsApp": "已用 WhatsApp 發送報價",
  "product stays in this category. Marketplace catalog uses the same name.": "件產品留在此分類。市集目錄使用同一個名稱。",
  "products stay in this category. Marketplace catalog uses the same name.": "件產品留在此分類。市集目錄使用同一個名稱。",
  "Chain SKUs will appear here and can be sent to Marketplace later. This list is not connected yet.": "Chain SKU 之後會出現在這裡，並可送到市集。此列表尚未連接。",
  "No Mattex Chain products yet. When this catalog is connected, selected SKUs can be published to Marketplace from here.": "尚未有 Mattex Chain 產品。目錄連接後，可在此把已選 SKU 上架到市集。",
  "Opened from Marketplace ·": "由市集打開 ·",
  "Buyer can still open the same RFQ under My RFQs.": "買家仍可在「我的 RFQ」打開同一張。",
  "Loading from Marketplace…": "正在從市集載入…",
  "is not in this inbox yet. Refresh, or wait a moment for Marketplace to sync.": "尚未在此收件箱。請重新整理，或稍候市集同步。",
  "Save name": "儲存名稱",
  "Confirm no offer": "確認無法報價",
  "Go to RFQ": "前往 RFQ",
  Dismiss: "略過",
  Acknowledge: "確認",
  "Reject (No Offer)": "拒絕（無法報價）",
  Open: "打開",
  "Accept the RFQ to start handling it. Buyer sees Submitted, then In review. Quotes and purchase orders stay hidden.": "確認 RFQ 後開始處理。買家會看到已提交，然後是處理中。報價和採購單仍會隱藏。",
};

export function adminText(lang, value) {
  if (lang !== "zh" || typeof value !== "string" || !value) return value;
  return Object.prototype.hasOwnProperty.call(ADMIN_ZH, value) ? ADMIN_ZH[value] : value;
}

